config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  resources :movies, only: [:index, :show] do
    collection do
      get 'search'
    end
    member do
      post 'add_to_favorites'
    end
  end
  resources :favorites, only: [:index]

  # Other routes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :favourites
  has_many :users, through: :favourites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_movies = fetch_favorite_movies
  rescue StandardError => e
    Rails.logger.error("An error occurred while fetching favorite movies: #{e.message}")
    @favorite_movies = [] # Set an empty array if an error occurs
  end

  private
  def fetch_favorite_movies
    Rails.logger.info("Fetch fav was called now")
    favorite_movie_ids = session[:fav_ids]
    Rails.logger.info("#{favorite_movie_ids}")
    return [] if favorite_movie_ids.blank?

    favorite_movies = []

    favorite_movie_ids.each do |movie_id|
      api_url = "https://api.themoviedb.org/3/movie/#{movie_id}?api_key=#{api_key}"

      response = HTTParty.get(api_url)
      movie_details = handle_api_response(response)
      favorite_movies << movie_details unless movie_details.empty?
    end

    favorite_movies
  end
  def handle_api_response(response)
    if response.success?
      JSON.parse(response.body)
    else
      Rails.logger.error("TMDb API error: Status code #{response.code}, Message: #{response.message}")
      [] # Return an empty array in case of API error
    end
  rescue JSON::ParserError => e
    Rails.logger.error("Error parsing TMDb API response: #{e.message}")
    [] # Return an empty array if JSON parsing fails
  end
  def api_key
    ENV['TMDB_API_KEY']
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  require 'themoviedb-api'

  before_action :initialize_session
  def index
    begin
      @latest_movie = fetch_upcoming_movies
      @movies = search_movies(params[:search]) if params[:search].present?
    rescue StandardError => e
      Rails.logger.error("An error occurred while fetching or searching movies: #{e.message}")
      @latest_movie = []
      @movies = []
    end
  end

  def show
    begin
      movie_id = params[:id]
      @movie_details = fetch_movie_details(movie_id)
    rescue StandardError => e
      Rails.logger.error("An error occurred while fetching movie details: #{e.message}")
      @movie_details = {}
    end
  end

  def add_to_favorites
    begin
      movie_id = params[:id]
      session[:fav_ids] << movie_id
      Rails.logger.info("#{session[:fav_ids]}")
      redirect_to movies_path, notice: 'Movie added to favorites!'
    rescue StandardError => e
      Rails.logger.error("An error occurred while adding movie to favorites: #{e.message}")
      redirect_to movies_path, alert: 'Error adding movie to favorites. Please try again.'
    end
  end

  private

  def initialize_session
    session[:fav_ids] ||= []
  end

  def fetch_upcoming_movies
    response = HTTParty.get("https://api.themoviedb.org/3/movie/upcoming?api_key=#{api_key}")
    JSON.parse(response.body)['results']
  end

  def search_movies(query)
    encoded_query = URI.encode_www_form_component(query)
    response = HTTParty.get("https://api.themoviedb.org/3/search/movie?api_key=#{api_key}&query=#{encoded_query}")
    JSON.parse(response.body)['results']
  end

  def fetch_movie_details(movie_id)
   
    response = HTTParty.get("https://api.themoviedb.org/3/movie/#{movie_id}?api_key=#{api_key}")
    JSON.parse(response.body)
  end

  def api_key
    ENV['TMDB_API_KEY']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/favorites/index.html.erb
<!-- app/views/favorites/index.html.erb -->
<h1>Favorite Movies</h1>

<% if @favorite_movies.present? %>
  <ul>
    <% @favorite_movies.each do |movie| %>
      <li>
        <h2><%= movie['title'] %></h2>
        <p>Release Date: <%= movie['release_date'] %></p>
        <p>Overview: <%= movie['overview'] %></p>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>You haven't added any favorite movies yet.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav>
  <%= link_to 'Home', root_path %>
  <%= link_to 'Favorite Movies', favorites_path %>
</nav>
    <%= yield %>
  </body>
</html>

app/views/movies/add_to_favorites.js.erb
alert('Movie added to favorites!');

app/views/movies/index.html.erb
<%= form_tag(movies_path, method: 'get', class: 'search-form') do %>
  <%= label_tag :search, 'Search by movie title' %>
  <%= text_field_tag :search, params[:search], class: 'search-field', placeholder: 'Enter movie title...' %>
  <%= submit_tag 'Search', class: 'search-button' %>
<% end %>

<% if @movies.present? %>
  <h1>Search Results</h1>
  <ul>
    <% @movies.each do |movie| %>
      <li>
        <%= link_to movie['title'], movie_path(movie['id']) %>
        <%= form_tag add_to_favorites_movie_path(movie['id']), method: :post, class: 'add-to-favorites-form' do %>
          <%= submit_tag 'Add to Favorites', class: 'add-to-favorites-button' %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
  <h1>Latest Movies</h1>
  <ul>
    <% @latest_movie.each do |movie| %>
      <li>
        <%= link_to movie['title'], movie_path(movie['id']) %>
        <%= form_tag add_to_favorites_movie_path(movie['id']), method: :post, class: 'add-to-favorites-form' do %>
          <%= submit_tag 'Add to Favorites', class: 'add-to-favorites-button' %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/movies/show.html.erb
<!-- app/views/movies/show.html.erb -->
<h1><%= @movie_details['title'] %></h1>
<p><strong>Overview:</strong> <%= @movie_details['overview'] %></p>
<p><strong>Release Date:</strong> <%= @movie_details['release_date'] %></p>
<p><strong>Vote Average:</strong> <%= @movie_details['vote_average'] %></p>

<%= link_to 'Back to Movie List', movies_path %>